# Generated by Django 5.2.17 on 2026-09-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dvkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.PositiveIntegerField(blank=True, null=True, verbose_name='STT')),
                ('ma_dich_vu', models.CharField(db_index=True, max_length=100, verbose_name='Mã dịch vụ')),
                ('ten_dich_vu', models.TextField(verbose_name='Tên dịch vụ')),
                ('ten_dvkt_gia', models.TextField(blank=True, verbose_name='Tên DVKT theo giá')),
                ('don_gia', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Đơn giá')),
                ('quy_trinh', models.TextField(blank=True, verbose_name='Quy trình')),
                ('so_luong_cgkt', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng chuyển giao kỹ thuật')),
                ('cskcb_cgkt', models.CharField(blank=True, max_length=255, verbose_name='CSKCB chuyển giao kỹ thuật')),
                ('cskcb_cls', models.CharField(blank=True, max_length=255, verbose_name='CSKCB cận lâm sàng')),
                ('qd_dvkt', models.TextField(blank=True, verbose_name='Quyết định DVKT')),
                ('qd_pd_gia', models.TextField(blank=True, verbose_name='Quyết định phê duyệt giá')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ma_thuoc', models.CharField(blank=True, max_length=255, verbose_name='Mã thuốc')),
                ('ten_thuoc', models.TextField(blank=True, verbose_name='Tên thuốc')),
                ('so_dang_ky', models.CharField(blank=True, max_length=255, verbose_name='Số đăng ký')),
                ('don_vi_tinh', models.CharField(blank=True, max_length=100, verbose_name='Đơn vị tính')),
                ('tt_thau', models.TextField(blank=True, verbose_name='Thông tin thầu')),
                ('don_gia_thuoc', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Đơn giá thuốc')),
                ('dm_nsx_cdd', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Định mức NSX CDD')),
                ('dm_thucte_cdd', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Định mức thực tế CDD')),
                ('lieu_bq_px', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Liều BQ PX')),
                ('tl_thucte_bq_px', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Tỷ lệ thực tế BQ PX')),
                ('thanh_tien_thuoc', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Thành tiền thuốc')),
                ('gia_thanh_toan', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Giá thanh toán')),
                ('tu_ngay', models.DateField(verbose_name='Từ ngày')),
                ('den_ngay', models.DateField(blank=True, null=True, verbose_name='Đến ngày')),
                ('ma_cskcb', models.CharField(db_index=True, max_length=20, verbose_name='Mã CSKCB')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Dịch vụ kỹ thuật',
                'verbose_name_plural': 'Dịch vụ kỹ thuật',
                'db_table': 'dvkt',
                'ordering': ['stt', 'ma_dich_vu'],
                'constraints': [models.UniqueConstraint(fields=('ma_cskcb', 'ma_dich_vu', 'tu_ngay'), name='dvkt_unique_service_date'), models.CheckConstraint(condition=models.Q(('den_ngay__isnull', True), ('den_ngay__gte', models.F('tu_ngay')), _connector='OR'), name='dvkt_valid_date_range')],
            },
        ),
    ]
