# Generated by Django 5.2.17 on 2026-09-26 13:29

import appointments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên chuyên khoa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang nhận lịch')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Chuyên khoa',
                'verbose_name_plural': 'Chuyên khoa',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(default=appointments.models.generate_booking_code, editable=False, max_length=11, unique=True, verbose_name='Mã đăng ký')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('phone_normalized', models.CharField(db_index=True, max_length=11, verbose_name='Số điện thoại chuẩn hóa')),
                ('requested_date', models.DateField(db_index=True, verbose_name='Ngày mong muốn')),
                ('status', models.CharField(choices=[('new', 'Mới tiếp nhận'), ('contacted', 'Đã liên hệ'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='new', max_length=20, verbose_name='Trạng thái')),
                ('consent_version', models.CharField(default='booking-v1', max_length=30, verbose_name='Phiên bản đồng ý')),
                ('consent_at', models.DateTimeField(verbose_name='Thời điểm đồng ý')),
                ('source', models.CharField(default='website', max_length=30, verbose_name='Nguồn')),
                ('idempotency_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('internal_note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.specialty', verbose_name='Chuyên khoa')),
            ],
            options={
                'verbose_name': 'Đăng ký khám',
                'verbose_name_plural': 'Đăng ký khám',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Từ trạng thái')),
                ('to_status', models.CharField(max_length=20, verbose_name='Đến trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointmentrequest')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['status', 'requested_date'], name='appt_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['specialty', 'requested_date'], name='appt_spec_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'contacted', 'confirmed'])), fields=('phone_normalized', 'specialty', 'requested_date'), name='unique_active_appointment'),
        ),
    ]
