# Generated by Django 5.2.17 on 2026-09-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_seed_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentrequest',
            name='unique_active_appointment',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='symptoms',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Mô tả triệu chứng'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.specialty', verbose_name='Chuyên khoa'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'contacted', 'confirmed'])), fields=('phone_normalized', 'specialty', 'requested_date'), name='unique_active_appointment', nulls_distinct=False),
        ),
    ]
