# Generated by Django 5.2.17 on 2026-10-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Bật/Tắt hiển thị khung Chatbot trên toàn bộ website.', verbose_name='Bật Chatbot trên Website')),
                ('bot_name', models.CharField(default='Trợ lý Y tế BV Lao & Bệnh Phổi Bạc Liêu', max_length=150, verbose_name='Tên Trợ lý ảo')),
                ('welcome_message', models.TextField(default='Xin chào! Tôi là Trợ lý AI Bệnh viện Lao và Bệnh phổi Bạc Liêu. Tôi có thể hỗ trợ bạn tra cứu lịch làm việc, thủ tục BHYT, triệu chứng hô hấp, hướng dẫn điều trị bệnh lao và bảng giá dịch vụ kỹ thuật.', verbose_name='Lời chào mở đầu')),
                ('emergency_hotline', models.CharField(default='0291 3 678 977', max_length=100, verbose_name='Hotline cấp cứu / Khẩn cấp')),
                ('disclaimer_text', models.TextField(default='Lưu ý y khoa: Thông tin do Trợ lý ảo cung cấp chỉ mang tính tham khảo và hướng dẫn thủ tục. Không thay thế cho việc khám bệnh, chẩn đoán và chỉ định điều trị trực tiếp từ Bác sĩ.', verbose_name='Tuyên bố miễn trừ trách nhiệm y tế')),
                ('quick_prompts_json', models.TextField(default='[\n  "🕒 Giờ làm việc & Lịch khám",\n  "💳 Khám BHYT cần giấy tờ gì?",\n  "🫁 Triệu chứng nghi ngờ Lao phổi",\n  "💰 Tra cứu giá X-quang & Xét nghiệm",\n  "🩺 Khám Hen phế quản & COPD",\n  "🚨 Dấu hiệu cấp cứu hô hấp"\n]', help_text='Danh sách nút bấm câu hỏi nhanh cho người bệnh chọn.', verbose_name='Danh sách gợi ý câu hỏi nhanh (JSON)')),
                ('fallback_message', models.TextField(default='Dạ, câu hỏi của bạn cần được bác sĩ chuyên khoa tư vấn chi tiết hơn. Bạn có thể nhấn **Đặt lịch khám** hoặc gọi hotline **0291 3 678 977** để nhân viên y tế hỗ trợ bạn ngay nhé.', verbose_name='Tin nhắn khi chưa tìm thấy câu trả lời')),
                ('enable_ai', models.BooleanField(default=False, help_text='Tùy chọn kết nối API AI nâng cao trong tương lai.', verbose_name='Bật AI nâng cao (LLM)')),
                ('ai_api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key AI (nếu dùng)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Cấu hình Chatbot',
                'verbose_name_plural': 'Cấu hình Chatbot',
                'db_table': 'chatbot_config',
            },
        ),
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TIEP_DON', '1. Đón tiếp & Giờ làm việc'), ('BHYT', '2. BHYT & Chuyển tuyến'), ('BENH_LAO', '3. Bệnh Lao & CT Chống Lao'), ('HO_HAP', '4. Bệnh Phổi - Hô hấp (Hen, COPD...)'), ('DVKT_GIA', '5. Bảng giá dịch vụ & Xét nghiệm'), ('CAP_CUU', '6. Cấp cứu & Dấu hiệu nguy hiểm'), ('TIEN_ICH', '7. Tiện ích & Liên hệ')], db_index=True, default='TIEP_DON', max_length=50, verbose_name='Chuyên mục')),
                ('question', models.CharField(db_index=True, max_length=500, verbose_name='Câu hỏi / Vấn đề')),
                ('answer', models.TextField(verbose_name='Nội dung trả lời chi tiết (Hỗ trợ Markdown)')),
                ('keywords', models.TextField(blank=True, help_text='Ví dụ: gio kham, thoi gian, may gio mo cua, thu 7 co lam khong', verbose_name='Từ khóa nhận diện (cách nhau bởi dấu phẩy)')),
                ('priority', models.IntegerField(default=0, verbose_name='Độ ưu tiên hiển thị')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Kích hoạt')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt tra cứu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Câu hỏi & Tri thức Chatbot',
                'verbose_name_plural': 'Câu hỏi & Tri thức Chatbot',
                'db_table': 'chatbot_faq',
                'ordering': ['category', '-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='Mã phiên chat')),
                ('user_message', models.TextField(verbose_name='Câu hỏi người dùng')),
                ('bot_response', models.TextField(verbose_name='Phản hồi của Chatbot')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Dấu hiệu khẩn cấp')),
                ('feedback', models.CharField(choices=[('none', 'Chưa đánh giá'), ('like', 'Hài lòng 👍'), ('dislike', 'Chưa hài lòng 👎')], default='none', max_length=20, verbose_name='Đánh giá của người dùng')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian')),
                ('matched_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='chatbot.chatbotfaq', verbose_name='FAQ tương ứng')),
            ],
            options={
                'verbose_name': 'Nhật ký hội thoại',
                'verbose_name_plural': 'Nhật ký hội thoại',
                'db_table': 'chatbot_chat_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
