# Generated by Django 5.2.17 on 2026-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Đường dẫn')),
                ('category', models.CharField(choices=[('news', 'Tin tức'), ('announcement', 'Thông báo')], db_index=True, default='news', max_length=20, verbose_name='Phân loại')),
                ('summary', models.CharField(max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('cover_image_url', models.CharField(blank=True, help_text='Ví dụ: ./assets/images/news-1.png. Để trống sẽ dùng ảnh mặc định.', max_length=300, verbose_name='Đường dẫn ảnh đại diện')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Tin nổi bật')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Thời điểm xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='news_status_pub_idx'), models.Index(fields=['category', 'published_at'], name='news_cat_pub_idx')],
            },
        ),
    ]
