# Generated by Django 5.2.17 on 2026-09-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_seed_news_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='news/%Y/%m/', verbose_name='Tập tin ảnh')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Chú thích ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newspost', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name': 'Hình ảnh bài viết',
                'verbose_name_plural': 'Hình ảnh bài viết',
                'ordering': ['created_at'],
            },
        ),
    ]
